// Mock data for vehicle management system

import { VehicleType, VehicleModel, Vehicle, Station } from '../types';

// Mock Vehicle Types
export const mockVehicleTypes: VehicleType[] = [
  {
    vehicle_type_id: 'vt-001',
    type_name: 'Sedan',
    description: '4-door sedan electric vehicles',
    created_at: new Date('2023-01-01'),
    isActive: true,
  },
  {
    vehicle_type_id: 'vt-002',
    type_name: 'SUV',
    description: 'Sport Utility Vehicle electric models',
    created_at: new Date('2023-01-01'),
    isActive: true,
  },
  {
    vehicle_type_id: 'vt-003',
    type_name: 'Hatchback',
    description: 'Compact hatchback electric cars',
    created_at: new Date('2023-01-01'),
    isActive: true,
  },
  {
    vehicle_type_id: 'vt-004',
    type_name: 'Luxury',
    description: 'Premium luxury electric vehicles',
    created_at: new Date('2023-01-01'),
    isActive: true,
  },
  {
    vehicle_type_id: 'vt-005',
    type_name: 'Crossover',
    description: 'Electric crossover vehicles',
    created_at: new Date('2023-01-01'),
    isActive: true,
  },
  {
    vehicle_type_id: 'vt-006',
    type_name: 'Compact',
    description: 'Compact electric city cars',
    created_at: new Date('2023-01-01'),
    isActive: true,
  }
];

// Mock Vehicle Models
export const mockVehicleModels: VehicleModel[] = [
  {
    vehicle_model_id: 'vm-001',
    type_id: 'vt-001',
    name: 'Model 3',
    manufacturer: 'Tesla',
    price_per_hour: 25,
    specs: 'Standard Range, 250km range, 0-100km/h in 5.3s',
    created_at: new Date('2023-01-01'),
    isActive: true,
  },
  {
    vehicle_model_id: 'vm-002',
    type_id: 'vt-001',
    name: 'Leaf',
    manufacturer: 'Nissan',
    price_per_hour: 20,
    specs: 'Plus trim, 300km range, 0-100km/h in 7.9s',
    created_at: new Date('2023-01-01'),
    isActive: true,
  },
  {
    vehicle_model_id: 'vm-003',
    type_id: 'vt-002',
    name: 'Model Y',
    manufacturer: 'Tesla',
    price_per_hour: 30,
    specs: 'Long Range, 500km range, 0-100km/h in 5.0s',
    created_at: new Date('2023-01-01'),
    isActive: true,
  },
  {
    vehicle_model_id: 'vm-004',
    type_id: 'vt-001',
    name: 'i3',
    manufacturer: 'BMW',
    price_per_hour: 30,
    specs: 'eDrive40, 300km range, 0-100km/h in 5.7s',
    created_at: new Date('2023-01-01'),
    isActive: true,
  },
  {
    vehicle_model_id: 'vm-005',
    type_id: 'vt-003',
    name: 'Kona EV',
    manufacturer: 'Hyundai',
    price_per_hour: 22,
    specs: 'Ultimate, 400km range, 0-100km/h in 7.6s',
    created_at: new Date('2023-01-01'),
    isActive: true,
  },
  {
    vehicle_model_id: 'vm-006',
    type_id: 'vt-004',
    name: 'e-tron GT',
    manufacturer: 'Audi',
    price_per_hour: 45,
    specs: 'Premium, 400km range, 0-100km/h in 4.1s',
    created_at: new Date('2023-01-01'),
    isActive: true,
  },
  {
    vehicle_model_id: 'vm-007',
    type_id: 'vt-005',
    name: 'ID.4',
    manufacturer: 'Volkswagen',
    price_per_hour: 28,
    specs: 'Pro, 450km range, 0-100km/h in 8.5s',
    created_at: new Date('2023-01-01'),
    isActive: true,
  },
  {
    vehicle_model_id: 'vm-008',
    type_id: 'vt-006',
    name: 'Zoe',
    manufacturer: 'Renault',
    price_per_hour: 18,
    specs: 'R135, 395km range, 0-100km/h in 9.5s',
    created_at: new Date('2023-01-01'),
    isActive: true,
  },
  {
    vehicle_model_id: 'vm-009',
    type_id: 'vt-002',
    name: 'Mustang Mach-E',
    manufacturer: 'Ford',
    price_per_hour: 35,
    specs: 'Extended Range, 600km range, 0-100km/h in 3.7s',
    created_at: new Date('2023-01-01'),
    isActive: true,
  },
  {
    vehicle_model_id: 'vm-010',
    type_id: 'vt-001',
    name: 'Polestar 2',
    manufacturer: 'Polestar',
    price_per_hour: 40,
    specs: 'Long Range, 540km range, 0-100km/h in 4.7s',
    created_at: new Date('2023-01-01'),
    isActive: true,
  }
];

// Mock Vehicles
export const mockVehicles: Vehicle[] = [
  // Station 1 vehicles
  {
    vehicle_id: 'v-001',
    serial_number: 'TSL-M3-001',
    model_id: 'vm-001',
    station_id: '1',
    status: 'AVAILABLE',
    battery_level: 85,
    battery_capacity: 60,
    range: 250,
    color: 'Pearl White',
    last_maintenance: new Date('2024-01-10'),
    img: 'https://images.pexels.com/photos/35967/mini-cooper-auto-model-vehicle.jpg?auto=compress&cs=tinysrgb&w=400',
    created_at: new Date('2023-06-01'),
    isActive: true,
  },
  {
    vehicle_id: 'v-002',
    serial_number: 'NSN-LEAF-002',
    model_id: 'vm-002',
    station_id: '1',
    status: 'AVAILABLE',
    battery_level: 92,
    battery_capacity: 62,
    range: 300,
    color: 'Blue',
    last_maintenance: new Date('2024-01-15'),
    img: 'https://images.pexels.com/photos/116675/pexels-photo-116675.jpeg?auto=compress&cs=tinysrgb&w=400',
    created_at: new Date('2023-07-01'),
    isActive: true,
  },
  {
    vehicle_id: 'v-003',
    serial_number: 'BMW-I3-003',
    model_id: 'vm-004',
    station_id: '1',
    status: 'RENTED',
    battery_level: 15,
    battery_capacity: 42,
    range: 300,
    color: 'Black',
    last_maintenance: new Date('2024-01-05'),
    img: 'https://images.pexels.com/photos/170811/pexels-photo-170811.jpeg?auto=compress&cs=tinysrgb&w=400',
    created_at: new Date('2023-08-01'),
    isActive: true,
  },
  {
    vehicle_id: 'v-004',
    serial_number: 'HYN-KONA-004',
    model_id: 'vm-005',
    station_id: '1',
    status: 'MAINTENANCE',
    battery_level: 78,
    battery_capacity: 64,
    range: 400,
    color: 'Silver',
    last_maintenance: new Date('2024-01-12'),
    img: 'https://images.pexels.com/photos/116675/pexels-photo-116675.jpeg?auto=compress&cs=tinysrgb&w=400',
    created_at: new Date('2023-09-01'),
    isActive: true,
  },
  {
    vehicle_id: 'v-005',
    serial_number: 'AUD-ETRON-005',
    model_id: 'vm-006',
    station_id: '1',
    status: 'AVAILABLE',
    battery_level: 88,
    battery_capacity: 93,
    range: 400,
    color: 'Red',
    last_maintenance: new Date('2024-01-08'),
    img: 'https://images.pexels.com/photos/170811/pexels-photo-170811.jpeg?auto=compress&cs=tinysrgb&w=400',
    created_at: new Date('2023-10-01'),
    isActive: true,
  },
  {
    vehicle_id: 'v-006',
    serial_number: 'TSL-MY-006',
    model_id: 'vm-003',
    station_id: '1',
    status: 'RENTED',
    battery_level: 45,
    battery_capacity: 75,
    range: 500,
    color: 'Midnight Silver',
    last_maintenance: new Date('2024-01-20'),
    img: 'https://images.pexels.com/photos/35967/mini-cooper-auto-model-vehicle.jpg?auto=compress&cs=tinysrgb&w=400',
    created_at: new Date('2023-11-01'),
    isActive: true,
  },
  // Station 2 vehicles
  {
    vehicle_id: 'v-007',
    serial_number: 'TSL-M3-007',
    model_id: 'vm-001',
    station_id: '2',
    status: 'AVAILABLE',
    battery_level: 95,
    battery_capacity: 60,
    range: 250,
    color: 'Deep Blue',
    last_maintenance: new Date('2024-01-18'),
    img: 'https://images.pexels.com/photos/35967/mini-cooper-auto-model-vehicle.jpg?auto=compress&cs=tinysrgb&w=400',
    created_at: new Date('2023-12-01'),
    isActive: true,
  },
  {
    vehicle_id: 'v-008',
    serial_number: 'NSN-LEAF-008',
    model_id: 'vm-002',
    station_id: '2',
    status: 'MAINTENANCE',
    battery_level: 30,
    battery_capacity: 62,
    range: 300,
    color: 'White',
    last_maintenance: new Date('2024-01-22'),
    img: 'https://images.pexels.com/photos/116675/pexels-photo-116675.jpeg?auto=compress&cs=tinysrgb&w=400',
    created_at: new Date('2023-12-15'),
    isActive: true,
  },
  {
    vehicle_id: 'v-009',
    serial_number: 'BMW-I3-009',
    model_id: 'vm-004',
    station_id: '2',
    status: 'RENTED',
    battery_level: 60,
    battery_capacity: 42,
    range: 300,
    color: 'Gray',
    last_maintenance: new Date('2024-01-14'),
    img: 'https://images.pexels.com/photos/170811/pexels-photo-170811.jpeg?auto=compress&cs=tinysrgb&w=400',
    created_at: new Date('2024-01-01'),
    isActive: true,
  },
  // Additional vehicles for Station 1
  {
    vehicle_id: 'v-010',
    serial_number: 'TSL-M3-010',
    model_id: 'vm-001',
    station_id: '1',
    status: 'CHARGING',
    battery_level: 25,
    battery_capacity: 60,
    range: 250,
    color: 'Pearl White',
    last_maintenance: new Date('2024-01-25'),
    img: 'https://images.pexels.com/photos/35967/mini-cooper-auto-model-vehicle.jpg?auto=compress&cs=tinysrgb&w=400',
    created_at: new Date('2023-06-15'),
    isActive: true,
  },
  {
    vehicle_id: 'v-011',
    serial_number: 'NSN-LEAF-011',
    model_id: 'vm-002',
    station_id: '1',
    status: 'AVAILABLE',
    battery_level: 100,
    battery_capacity: 62,
    range: 300,
    color: 'Green',
    last_maintenance: new Date('2024-01-28'),
    img: 'https://images.pexels.com/photos/116675/pexels-photo-116675.jpeg?auto=compress&cs=tinysrgb&w=400',
    created_at: new Date('2023-07-15'),
    isActive: true,
  },
  {
    vehicle_id: 'v-012',
    serial_number: 'TSL-MY-012',
    model_id: 'vm-003',
    station_id: '1',
    status: 'AVAILABLE',
    battery_level: 90,
    battery_capacity: 75,
    range: 500,
    color: 'Red',
    last_maintenance: new Date('2024-01-30'),
    img: 'https://images.pexels.com/photos/35967/mini-cooper-auto-model-vehicle.jpg?auto=compress&cs=tinysrgb&w=400',
    created_at: new Date('2023-08-15'),
    isActive: true,
  },
  {
    vehicle_id: 'v-013',
    serial_number: 'BMW-I3-013',
    model_id: 'vm-004',
    station_id: '1',
    status: 'MAINTENANCE',
    battery_level: 50,
    battery_capacity: 42,
    range: 300,
    color: 'Blue',
    last_maintenance: new Date('2024-02-01'),
    img: 'https://images.pexels.com/photos/170811/pexels-photo-170811.jpeg?auto=compress&cs=tinysrgb&w=400',
    created_at: new Date('2023-09-15'),
    isActive: true,
  },
  {
    vehicle_id: 'v-014',
    serial_number: 'HYN-KONA-014',
    model_id: 'vm-005',
    station_id: '1',
    status: 'RENTED',
    battery_level: 35,
    battery_capacity: 64,
    range: 400,
    color: 'Black',
    last_maintenance: new Date('2024-01-29'),
    img: 'https://images.pexels.com/photos/116675/pexels-photo-116675.jpeg?auto=compress&cs=tinysrgb&w=400',
    created_at: new Date('2023-10-15'),
    isActive: true,
  },
  {
    vehicle_id: 'v-015',
    serial_number: 'AUD-ETRON-015',
    model_id: 'vm-006',
    station_id: '1',
    status: 'CHARGING',
    battery_level: 20,
    battery_capacity: 93,
    range: 400,
    color: 'Silver',
    last_maintenance: new Date('2024-01-27'),
    img: 'https://images.pexels.com/photos/170811/pexels-photo-170811.jpeg?auto=compress&cs=tinysrgb&w=400',
    created_at: new Date('2023-11-15'),
    isActive: true,
  },
  {
    vehicle_id: 'v-016',
    serial_number: 'TSL-M3-016',
    model_id: 'vm-001',
    station_id: '1',
    status: 'AVAILABLE',
    battery_level: 75,
    battery_capacity: 60,
    range: 250,
    color: 'Midnight Silver',
    last_maintenance: new Date('2024-01-26'),
    img: 'https://images.pexels.com/photos/35967/mini-cooper-auto-model-vehicle.jpg?auto=compress&cs=tinysrgb&w=400',
    created_at: new Date('2023-12-15'),
    isActive: true,
  },
  {
    vehicle_id: 'v-017',
    serial_number: 'NSN-LEAF-017',
    model_id: 'vm-002',
    station_id: '1',
    status: 'RENTED',
    battery_level: 40,
    battery_capacity: 62,
    range: 300,
    color: 'Orange',
    last_maintenance: new Date('2024-01-24'),
    img: 'https://images.pexels.com/photos/116675/pexels-photo-116675.jpeg?auto=compress&cs=tinysrgb&w=400',
    created_at: new Date('2024-01-15'),
    isActive: true,
  },
  {
    vehicle_id: 'v-018',
    serial_number: 'TSL-MY-018',
    model_id: 'vm-003',
    station_id: '1',
    status: 'MAINTENANCE',
    battery_level: 65,
    battery_capacity: 75,
    range: 500,
    color: 'White',
    last_maintenance: new Date('2024-02-02'),
    img: 'https://images.pexels.com/photos/35967/mini-cooper-auto-model-vehicle.jpg?auto=compress&cs=tinysrgb&w=400',
    created_at: new Date('2024-01-20'),
    isActive: true,
  },
  {
    vehicle_id: 'v-019',
    serial_number: 'BMW-I3-019',
    model_id: 'vm-004',
    station_id: '1',
    status: 'AVAILABLE',
    battery_level: 95,
    battery_capacity: 42,
    range: 300,
    color: 'Yellow',
    last_maintenance: new Date('2024-01-23'),
    img: 'https://images.pexels.com/photos/170811/pexels-photo-170811.jpeg?auto=compress&cs=tinysrgb&w=400',
    created_at: new Date('2024-01-25'),
    isActive: true,
  },
  {
    vehicle_id: 'v-020',
    serial_number: 'HYN-KONA-020',
    model_id: 'vm-005',
    station_id: '1',
    status: 'CHARGING',
    battery_level: 15,
    battery_capacity: 64,
    range: 400,
    color: 'Purple',
    last_maintenance: new Date('2024-01-21'),
    img: 'https://images.pexels.com/photos/116675/pexels-photo-116675.jpeg?auto=compress&cs=tinysrgb&w=400',
    created_at: new Date('2024-01-30'),
    isActive: true,
  },
  // Additional vehicles with new models
  {
    vehicle_id: 'v-021',
    serial_number: 'VW-ID4-021',
    model_id: 'vm-007',
    station_id: '1',
    status: 'AVAILABLE',
    battery_level: 80,
    battery_capacity: 77,
    range: 450,
    color: 'Blue',
    last_maintenance: new Date('2024-01-19'),
    img: 'https://images.pexels.com/photos/116675/pexels-photo-116675.jpeg?auto=compress&cs=tinysrgb&w=400',
    created_at: new Date('2024-02-01'),
    isActive: true,
  },
  {
    vehicle_id: 'v-022',
    serial_number: 'REN-ZOE-022',
    model_id: 'vm-008',
    station_id: '1',
    status: 'RENTED',
    battery_level: 55,
    battery_capacity: 52,
    range: 395,
    color: 'White',
    last_maintenance: new Date('2024-01-17'),
    img: 'https://images.pexels.com/photos/170811/pexels-photo-170811.jpeg?auto=compress&cs=tinysrgb&w=400',
    created_at: new Date('2024-02-02'),
    isActive: true,
  },
  {
    vehicle_id: 'v-023',
    serial_number: 'FRD-MACH-023',
    model_id: 'vm-009',
    station_id: '1',
    status: 'MAINTENANCE',
    battery_level: 70,
    battery_capacity: 88,
    range: 600,
    color: 'Grabber Blue',
    last_maintenance: new Date('2024-02-03'),
    img: 'https://images.pexels.com/photos/35967/mini-cooper-auto-model-vehicle.jpg?auto=compress&cs=tinysrgb&w=400',
    created_at: new Date('2024-02-03'),
    isActive: true,
  },
  {
    vehicle_id: 'v-024',
    serial_number: 'POL-2-024',
    model_id: 'vm-010',
    station_id: '1',
    status: 'CHARGING',
    battery_level: 30,
    battery_capacity: 78,
    range: 540,
    color: 'Thunder',
    last_maintenance: new Date('2024-01-16'),
    img: 'https://images.pexels.com/photos/170811/pexels-photo-170811.jpeg?auto=compress&cs=tinysrgb&w=400',
    created_at: new Date('2024-02-04'),
    isActive: true,
  },
  {
    vehicle_id: 'v-025',
    serial_number: 'VW-ID4-025',
    model_id: 'vm-007',
    station_id: '1',
    status: 'AVAILABLE',
    battery_level: 100,
    battery_capacity: 77,
    range: 450,
    color: 'Moonstone Gray',
    last_maintenance: new Date('2024-01-14'),
    img: 'https://images.pexels.com/photos/116675/pexels-photo-116675.jpeg?auto=compress&cs=tinysrgb&w=400',
    created_at: new Date('2024-02-05'),
    isActive: true,
  },
  {
    vehicle_id: 'v-026',
    serial_number: 'REN-ZOE-026',
    model_id: 'vm-008',
    station_id: '1',
    status: 'RENTED',
    battery_level: 25,
    battery_capacity: 52,
    range: 395,
    color: 'Flame Red',
    last_maintenance: new Date('2024-01-13'),
    img: 'https://images.pexels.com/photos/170811/pexels-photo-170811.jpeg?auto=compress&cs=tinysrgb&w=400',
    created_at: new Date('2024-02-06'),
    isActive: true,
  },
  {
    vehicle_id: 'v-027',
    serial_number: 'FRD-MACH-027',
    model_id: 'vm-009',
    station_id: '1',
    status: 'AVAILABLE',
    battery_level: 90,
    battery_capacity: 88,
    range: 600,
    color: 'Infinite Blue',
    last_maintenance: new Date('2024-01-12'),
    img: 'https://images.pexels.com/photos/35967/mini-cooper-auto-model-vehicle.jpg?auto=compress&cs=tinysrgb&w=400',
    created_at: new Date('2024-02-07'),
    isActive: true,
  },
  {
    vehicle_id: 'v-028',
    serial_number: 'POL-2-028',
    model_id: 'vm-010',
    station_id: '1',
    status: 'CHARGING',
    battery_level: 10,
    battery_capacity: 78,
    range: 540,
    color: 'Magnesium',
    last_maintenance: new Date('2024-01-11'),
    img: 'https://images.pexels.com/photos/170811/pexels-photo-170811.jpeg?auto=compress&cs=tinysrgb&w=400',
    created_at: new Date('2024-02-08'),
    isActive: true,
  }
];

// Helper functions
export const getVehicleTypeById = (id: string): VehicleType | undefined => {
  return mockVehicleTypes.find(type => type.vehicle_type_id === id);
};

export const getVehicleModelById = (id: string): VehicleModel | undefined => {
  return mockVehicleModels.find(model => model.vehicle_model_id === id);
};

export const getVehicleById = (id: string): Vehicle | undefined => {
  return mockVehicles.find(vehicle => vehicle.vehicle_id === id);
};

export const getVehiclesByStation = (stationId: string): Vehicle[] => {
  return mockVehicles.filter(vehicle => vehicle.station_id === stationId);
};

export const getVehiclesByStatus = (status: Vehicle['status']): Vehicle[] => {
  return mockVehicles.filter(vehicle => vehicle.status === status);
};

// Get vehicle with full details (including model and type info)
export const getVehicleWithDetails = (vehicleId: string) => {
  const vehicle = getVehicleById(vehicleId);
  if (!vehicle) return null;

  const model = getVehicleModelById(vehicle.model_id);
  if (!model) return null;

  const type = getVehicleTypeById(model.type_id);
  if (!type) return null;

  return {
    ...vehicle,
    model: {
      ...model,
      type
    }
  };
};

// Mock Stations
export const mockStations: Station[] = [
  {
    id: '1',
    name: 'Downtown Hub',
    address: '123 Main Street, Downtown',
    coordinates: { lat: 40.7128, lng: -74.0060 },
    availableVehicles: 8,
    totalVehicles: 12,
    status: 'active',
    facilities: ['Fast Charging', 'Parking', '24/7 Access', 'WiFi']
  },
  {
    id: '2',
    name: 'Airport Terminal',
    address: '456 Airport Blvd, Terminal B',
    coordinates: { lat: 40.6892, lng: -74.1745 },
    availableVehicles: 3,
    totalVehicles: 15,
    status: 'active',
    facilities: ['Fast Charging', 'Covered Parking', 'Security']
  },
  {
    id: '3',
    name: 'University Campus',
    address: '789 College Ave, Campus Center',
    coordinates: { lat: 40.7282, lng: -74.0776 },
    availableVehicles: 0,
    totalVehicles: 8,
    status: 'maintenance',
    facilities: ['Standard Charging', 'Student Discounts', 'Bike Racks']
  }
];
